config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :home, only: [:index]
  resources :projects, only: [:index, :show]
  resources :about, only: [:index]
  resources :contact, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About</h1>

app/views/contact/index.html.erb
<h1>Contact</h1>

<ul>
  <li>Email: <%=mail_to "rahaynes@gmail.com"%></li>
  <li>Cell: <a href="tel: 828-719-7689">828-719-7689</a></li>
  <li>LinkedIn: <%=link_to 'https://www.linkedin.com/in/robertandersonhaynes/'%></li>
</ul>

app/views/home/index.html.erb
<h1>Robert Anderson Haynes - Full Stack Developer</h1>

<h3><%= link_to 'Home', home_index_path %></h3>
<h3><%= link_to 'About', about_index_path %></h3>
<h3><%= link_to 'Projects', projects_path %></h3>
<h3><%= link_to 'Contact', contact_index_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.title, project.url, target: :_blank %></li>
  <% end %>
</ul>